- name: config hosts file
  template: src=hosts.j2 dest=/etc/hosts

- name: config zookeeper cluster
  template: src=zoo.j2 dest=/etc/kafka/zookeeper.properties

- name: copy service script
  copy: src=../../../services/zookeeper-server dest=/etc/init.d/zookeeper-server mode=0754

- name: create log dirs
  file: path=/var/lib/zookeeper state=directory

- name: set myid file
  template: src=myid.j2 dest=/var/lib/zookeeper/myid

- name: run zookeeper
  service: name=zookeeper-server state=restarted
