- name : Gather facts zookeeper
  hosts: zookeeper
  become: yes
  gather_facts: yes
  remote_user: ubuntu

- name : Start Confluent Kafka Server
  hosts: kafka-server
  sudo: yes
  gather_facts: yes
  vars:
    action: 'install'
  remote_user: ubuntu
  roles:
    - common
    - kafka-server
