- name: config hosts file
  template: src=hosts.j2 dest=/etc/hosts

- name: config kafka server cluster
  template: src=server.j2 dest=/etc/kafka/server.properties

- name: copy service script
  copy: src=../../../services/kafka-server.service dest=/lib/systemd/system/kafka-server.service mode=0754

- name: copy init script
  copy: src=../../../services/kafka-server dest=/etc/init.d/kafka-server mode=0754

- name: create log dirs
  file: path=/var/lib/kafka state=directory

- name: config kafka metadata
  template: src=meta.j2 dest=/var/lib/kafka/meta.properties

- name: run kafka
  service: name=kafka-server state=restarted
