- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes


- name: install confluent platform
  apt: name=software-properties-common state=latest

- name: add java repository
  apt_repository: repo='ppa:openjdk-r/ppa' update_cache=yes

- name: Install Oracle Java 8
  apt: name=openjdk-8-jdk state=latest

- name: install confluent {{confluent_version}} public key
  apt_key: url=http://packages.confluent.io/deb/{{confluent_version}}/archive.key state=present

- name: add confluent {{confluent_version}} apt repository
  apt_repository: repo='deb https://packages.confluent.io/deb/{{confluent_version}} stable main' state=present update_cache=yes

- name: install confluent platform
  apt: name=confluent-platform-2.12 state=present
